#!/usr/bin/env python3
"""Check connection via ping.

Checks connections via ping on a list of hosts. If one host is available,
it marks the connection as green.
"""
from os import environ
from subprocess import PIPE, run
from typing import List, Optional

GREY = "#7f7f7f"
GREEN = "#50fa7b"
YELLOW = "#f1fa8c"


def run_ping(hosts: List[str]) -> List[int]:
    """Ping host."""
    exit_codes: List[int] = []
    for host in hosts:
        proc = run(["ping", "-c1", "-w1", host], stdout=PIPE, stderr=PIPE)
        exit_codes.append(proc.returncode)
    return exit_codes


def get_color(return_codes: List[int]) -> Optional[str]:
    """Calculates colors from list."""
    quota = (100/len(return_codes))*len([i for i in return_codes if i == 0])
    if quota > 50:
        return GREEN
    if 50 <= quota > 0:
        return YELLOW
    if quota == 0:
        return GREY
    return None


def main() -> str:
    """Entrypoint."""
    conn_name = environ["BLOCK_NAME"]
    hosts: List[str] = environ["BLOCK_INSTANCE"].split(" ")
    pings = run_ping(hosts)
    color = get_color(pings)
    print('<span color="{}">{}</span>'.format(color, conn_name))


if __name__ == "__main__":
    main()
