#!/usr/bin/env python3

import multiprocessing
import os


def load_fmt(load):
    cores = multiprocessing.cpu_count()
    color = '#f8f8f2'

    if load > cores * 0.5:
        color = '#f1fa8c'

    if load > cores * 0.7:
        color = '#ff5555'

    return '<span color="{}">{:.2f}</span>'.format(color, load)


def main():
    load1, load5, load15 = os.getloadavg()

    print('\uf085 {}, {}, {}'.format(
        load_fmt(load1),
        load_fmt(load5),
        load_fmt(load15),
    ))


if __name__ == '__main__':
    main()
