### antigen
source ~/.antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundles <<EOBUNDLES
    arialdomartini/oh-my-git
    common-aliases
    command-not-found
    dircycle
    gitfast
    kennethreitz/autoenv
    pip
    python
    sudo
    zsh-users/zsh-autosuggestions
    zsh-users/zsh-completions
    zsh-users/zsh-syntax-highlighting
EOBUNDLES

antigen theme ys

antigen apply

### export stuff
export EDITOR=/usr/bin/nvim
export PYENV_ROOT=$HOME/.pyenv
export PATH=~/.pyenv/shims:$PYENV_ROOT/bin:~/.local/bin:$PATH

### pyenv
which pyenv >/dev/null && { eval "$(pyenv init -)" }

### disable strange lock
stty -ixon

### aliases
alias vim=nvim
alias ll="ls -la"
