source ~/.antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundles <<EOBUNDLES
    arialdomartini/oh-my-git
    command-not-found
    dircycle
    gitfast
    kennethreitz/autoenv
    pip
    python
    sudo
    zsh-users/zsh-autosuggestions
    zsh-users/zsh-syntax-highlighting
EOBUNDLES

antigen theme ys

antigen apply
