#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source ~/.bash_aliases
export PATH=$PATH:~/.local/bin:~/miniconda3/bin
export EDITOR=vim

# ignore history for jrnl
setopt HIST_IGNORE_SPACE
alias jrnl=" jrnl"
