version: "3"

includes:
  docker:
    taskfile: ~/.tasks/docker.yml
    internal: true
  photoprism: ~/.tasks/photoprism/Taskfile.yml
  yt: ~/.tasks/youtube/Taskfile.yml
  caddy: ~/.tasks/lorelei/caddy/Taskfile.yml
  restic:
    taskfile: ~/.tasks/restic/Taskfile.yml
    internal: true

tasks:
  ps:
    cmds:
      - task: docker:ps

  xsfx:monitoring:
    cmds:
      - echo foo

  backup:run:
    cmds:
      - task: restic:backup
    requires:
      vars:
        - HOST
