#!/usr/bin/env python3
"""Check vpn via ping.

Checks VPN connection via ping on a list of hosts. If one host is available,
it marks the vpn as green.
"""
from subprocess import PIPE, run
from sys import argv
from typing import List

GREY = "#6272a4"
GREEN = "#50fa7b"


def run_ping(hosts: List[str]) -> bool:
    """Ping host."""
    exit_codes: List[bool] = []
    for host in hosts:
        proc = run(["ping", "-c1", "-w1", host], stdout=PIPE, stderr=PIPE)
        if proc.returncode == 0:
            exit_codes.append(True)
        else:
            exit_codes.append(False)
    if True in exit_codes:
        return True
    return False


def main(arguments: List[str]) -> str:
    """Entrypoint."""
    vpn_name = arguments[0]
    hosts = arguments[1:]
    ping = run_ping(hosts)
    if ping is True:
        color = GREEN
    else:
        color = GREY
    print('<span color="{}">{}</span>'.format(color, vpn_name))


if __name__ == "__main__":
    main(argv[1:])
