#!/bin/sh

SPICE_PORT=5924
sudo qemu-system-x86_64 \
    -enable-kvm \
    -machine q35,accel=kvm \
    -daemonize  \
    -m 4G \
    -vga qxl \
    -spice port=${SPICE_PORT},disable-ticketing \
    -drive file=/home/preuss/qemu-images/alpine.qcow2,if=virtio \
    -device ich9-usb-ehci1,id=usb \
    -device ich9-usb-uhci1,masterbus=usb.0,firstport=0,multifunction=on \
    -device ich9-usb-uhci2,masterbus=usb.0,firstport=2 \
    -device ich9-usb-uhci3,masterbus=usb.0,firstport=4 \
    -chardev spicevmc,name=usbredir,id=usbredirchardev1 \
    -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1 \
    -chardev spicevmc,name=usbredir,id=usbredirchardev2 \
    -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2 \
    -chardev spicevmc,name=usbredir,id=usbredirchardev3 \
    -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3
exec spicy --title Windows 127.0.0.1 -p ${SPICE_PORT}
