version: "3.5"
services:
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.97.1
    # ports:
    # - 8428:8428
    # - 8089:8089
    # - 8089:8089/udp
    volumes:
      - victoriametrics-data:/storage
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
      # - "--influxListenAddr=:8089"
      - "--vmalert.proxyURL=http://vmalert:8880"
    networks:
      - http_backend
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  vmagent:
    container_name: vmwagent
    build:
      context: ./vmagent/
    depends_on:
      - victoriametrics
    volumes:
      - vmagent-data:/vmagentdata
    secrets:
      - UPTIME_KUMA_PASSWORD
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    networks:
      - http_backend
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  vmalert:
    container_name: vmalert
    build:
      context: ./vmalert/
    depends_on:
      - "victoriametrics"
      - "alertmanager"
    command:
      - "--datasource.url=http://victoriametrics:8428/"
      - "--remoteRead.url=http://victoriametrics:8428/"
      - "--remoteWrite.url=http://victoriametrics:8428/"
      - "--notifier.url=http://alertmanager:9093/"
      - "--rule=/etc/alerts/*.yml"
      - "--external.url=https://metrics.mon.xsfx.dev"
    networks:
      - http_backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  alertmanager:
    container_name: alertmanager
    build:
      context: ./alertmanager/
    # ports:
    #   - 9093:9093
    command:
      - "--config.file=/config/alertmanager.yml"
    networks:
      - http_backend
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    secrets:
      - TELEGRAM_BOT_TOKEN
  grafana:
    container_name: grafana
    build:
      context: ./grafana/
    depends_on:
      - victoriametrics
    # ports:
    #   - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - http_backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  blackbox_exporter:
    container_name: blackbox_exporter
    image: quay.io/prometheus/blackbox-exporter:v0.24.0
volumes:
  vmagent-data:
  victoriametrics-data:
  grafana-data:
networks:
  http_backend:
    external: true
secrets:
  UPTIME_KUMA_PASSWORD:
    environment: UPTIME_KUMA_PASSWORD
  TELEGRAM_BOT_TOKEN:
    environment: TELEGRAM_BOT_TOKEN
