# vim: set ft=yaml.docker-compose:
services:
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.97.1
    volumes:
      - victoriametrics-data:/storage
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
      - "--vmalert.proxyURL=http://vmalert:8880"
    networks:
      - http_backend
    restart: always
    logging: &logging
      driver: "json-file"
      options:
        max-size: "10m"
  vmagent:
    container_name: vmagent
    build:
      context: ./vmagent/
    depends_on:
      - victoriametrics
    volumes:
      - vmagent-data:/vmagentdata
    secrets:
      - UPTIME_KUMA_PASSWORD
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    networks:
      - http_backend
    restart: always
    logging: *logging
  vmalert:
    container_name: vmalert
    build:
      context: ./vmalert/
    depends_on:
      - "victoriametrics"
      - "alertmanager"
    command:
      - "--datasource.url=http://victoriametrics:8428/"
      - "--remoteRead.url=http://victoriametrics:8428/"
      - "--remoteWrite.url=http://victoriametrics:8428/"
      - "--notifier.url=http://alertmanager:9093/"
      - "--rule=/etc/alerts/*.yml"
      - "--external.url=https://metrics.mon.xsfx.dev"
    networks:
      - http_backend
    logging: *logging
    restart: always
  alertmanager:
    container_name: alertmanager
    build:
      context: ./alertmanager/
    command:
      - "--config.file=/config/alertmanager.yml"
      - "--storage.path=/data"
    networks:
      - http_backend
    restart: always
    logging: *logging
    secrets:
      - TELEGRAM_BOT_TOKEN
    volumes:
      - alertmanager-data:/data
  grafana:
    container_name: grafana
    build:
      context: ./grafana/
    depends_on:
      - victoriametrics
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - http_backend
    logging: *logging
    environment:
      GF_INSTALL_PLUGINS: "grafana-polystat-panel,grafana-piechart-panel"
    restart: always
  blackbox_exporter:
    container_name: blackbox_exporter
    image: quay.io/prometheus/blackbox-exporter:v0.24.0
    networks:
      - http_backend
    logging: *logging
    restart: always
  gitlab_exporter:
    container_name: gitlab_exporter
    build:
      context: ./gitlab_exporter/
    environment:
      GCPE_GITLAB_TOKEN: ${GCPE_GITLAB_TOKEN}
    command: run --config /etc/config.yml
    networks:
      - http_backend
    logging: *logging
    restart: always
  glucose_exporter:
    container_name: glucose_exporter
    image: ghcr.io/xsteadfastx/glucose_exporter:0.1.0-rc4
    secrets:
      - GLUCOSE_PASSWORD
    volumes:
      - glucose_exporter-data:/var/cache/glucose_exporter
    environment:
      EMAIL: marv@xsfx.dev
      PASSWORD_FILE: /run/secrets/GLUCOSE_PASSWORD
      DEBUG: true
    networks:
      - http_backend
    logging: *logging
    restart: always
  nextcloud_exporter:
    container_name: nextcloud_exporter
    image: ghcr.io/xperimental/nextcloud-exporter:0.7.0
    environment:
      NEXTCLOUD_SERVER: ${NEXTCLOUD_SERVER}
      NEXTCLOUD_AUTH_TOKEN: ${NEXTCLOUD_AUTH_TOKEN}
      NEXTCLOUD_INFO_APPS: true
    networks:
      - http_backend
    logging: *logging
    restart: always
volumes:
  alertmanager-data:
  glucose_exporter-data:
  grafana-data:
  victoriametrics-data:
  vmagent-data:
networks:
  http_backend:
    external: true
secrets:
  UPTIME_KUMA_PASSWORD:
    environment: UPTIME_KUMA_PASSWORD
  TELEGRAM_BOT_TOKEN:
    environment: TELEGRAM_BOT_TOKEN
  GLUCOSE_PASSWORD:
    environment: GLUCOSE_PASSWORD
