version: "3"

includes:
  docker:
    taskfile: ~/.tasks/docker.yml
    internal: true

env:
  UPTIME_KUMA_PASSWORD:
    sh: gopass show -o websites/status.xsfx.dev/marv

  TELEGRAM_BOT_TOKEN:
    sh: gopass show -o misc/telegram-bot-status bot_token

  GCPE_GITLAB_TOKEN:
    sh: gopass show -o WOBCOM/gitlab/token

  GLUCOSE_PASSWORD:
    sh: gopass show -o misc/librelinkup/marv@xsfx.dev

tasks:
  restart:
    cmds:
      - task: build
      - task: down
      - task: up

  build:
    cmds:
      - task: docker:compose
        vars:
          DOCKER_COMPOSE_ARGS: build
  up:
    vars:
      NEXTCLOUD_SERVER:
        sh: gopass show -o misc/roehrscloud/serverinfo_token server
      NEXTCLOUD_AUTH_TOKEN:
        sh: gopass show -o misc/roehrscloud/serverinfo_token
    cmds:
      - echo "NEXTCLOUD_SERVER={{.NEXTCLOUD_SERVER}}" > .env
      - echo "NEXTCLOUD_AUTH_TOKEN={{.NEXTCLOUD_AUTH_TOKEN}}" >> .env
      - defer: rm .env

      - task: docker:network
        vars:
          NETWORK: http_backend

      - task: docker:compose
        vars:
          DOCKER_COMPOSE_ARGS: up -d

  down:
    cmds:
      - task: docker:compose
        vars:
          DOCKER_COMPOSE_ARGS: down

  logs:
    cmds:
      - task: docker:compose
        vars:
          DOCKER_COMPOSE_ARGS: logs -f

  ps:
    cmds:
      - task: docker:compose
        vars:
          DOCKER_COMPOSE_ARGS: ps
