version: "3"

includes:
  docker:
    taskfile: ~/.tasks/docker.yml
    internal: true

tasks:
  build:
    cmds:
      - task: docker:bin
        vars:
          DOCKER_ARGS: build -t airmtp:latest .
          DIR: .
    status:
      - '[ ! -z $(docker images -q airmtp:latest) ]'

  import:
    desc: import photos from my sony alpha
    summary: needs date in format like "mm/dd/yy"
    deps:
      - build
    cmds:
      - task: docker:bin
        vars:
          DOCKER_ARGS: "run --rm -ti -v {{.OUTPUT_DIR}}:/mnt --net=host airmtp:latest --ipaddress auto --outputdir /mnt --startdate {{.START_DATE}}"
    vars:
      NOW_DEFAULT: '{{ now | date "01/02/06" }}'
      START_DATE: "{{default .NOW_DEFAULT .START_DATE}}"
    requires:
      vars:
        - OUTPUT_DIR
