# vim: set ft=taskfile
version: "3"

includes:
  airmtp:
    taskfile: ~/.tasks/airmtp/Taskfile.yml
    internal: true

tasks:
  import:
    desc: gets photos from sony alpha cam and copies them to photoprism import
    cmds:
      - defer: rm -rf {{.DIR}}
      - airmtp --ipaddress auto --outputdir {{.DIR}} --startdate {{toDate "02/01/2006" .START_DATE | date "01/02/06"}}
      - "rclone copy -P {{.DIR}} photoprism-import:"
    vars:
      NOW: '{{now|date "02/01/2006"}}'
      START_DATE: "{{default .NOW .START_DATE}}"
      DIR:
        sh: mktemp -p ~/tmp -d -t photoprism-XXXXXXX
