global:
  scrape_interval: 30s
scrape_configs:
  - job_name: node_exporter
    scheme: http
    static_configs:
      - targets:
          - "abed.ts.xsfx.dev:9100"
          - "castlelabs.ts.xsfx.dev:9100"
          - "dalek.ts.xsfx.dev:9100"
          - "dipper.ts.xsfx.dev:9100"
          - "lorelei.ts.xsfx.dev:9100"
  - job_name: coredns
    scheme: http
    static_configs:
      - targets:
          - "dalek.ts.xsfx.dev:9153"
  - job_name: gitea
    scheme: https
    static_configs:
      - targets:
          - "git.xsfx.dev:443"
  - job_name: uptime
    scheme: https
    static_configs:
      - targets:
          - "status.mon.xsfx.dev"
    basic_auth:
      username: marv
      password_file: /run/secrets/UPTIME_KUMA_PASSWORD
  - job_name: caddy
    scheme: http
    static_configs:
      - targets:
          - "lorelei.ts.xsfx.dev:2019"
