global:
  scrape_interval: 1m
scrape_config_files:
  - "configs/*.yml"
scrape_configs:
  - job_name: uptime
    scheme: https
    static_configs:
      - targets:
          - "status.mon.xsfx.dev"
    basic_auth:
      username: marv
      password_file: /run/secrets/UPTIME_KUMA_PASSWORD
