---
- name: install deps
  package:
    state: latest
    name:
      - compton
      - dunst
      - feh
      - i3blocks
      - i3lock-fancy
      - i3status
      - rofi
      - xautolock
      - xdotool
  become: true

- name: compile and install gaps
  block:
    - name: debian | gaps | uninstall i3
      apt:
        name:
          - i3
          - i3-wm
        state: absent
      become: true
    - name: debian | gaps | needed dirs
      file:
        path: ~/src
        state: directory
    - name: debian | clone i3-gaps
      git:
        repo: https://github.com/Airblader/i3.git
        dest: ~/src/i3-gaps
      become: true
    - name: debian | gaps | install deps
      apt:
        name:
          - autoconf
          - automake
          - libev-dev
          - libpango1.0-dev
          - libstartup-notification0-dev
          - libxcb-cursor-dev
          - libxcb-icccm4-dev
          - libxcb-keysyms1-dev
          - libxcb-randr0-dev
          - libxcb-shape0-dev
          - libxcb-util0-dev
          - libxcb-xinerama0-dev
          - libxcb-xkb-dev
          - libxcb-xrm-dev
          - libxcb-xrm0
          - libxcb1-dev
          - libxkbcommon-dev
          - libxkbcommon-x11-dev
          - libyajl-dev
        state: latest
      become: true
    - name: debian | gaps | create build dir
      file:
        path: ~/src/i3-gaps/build
        state: "{{ item }}"
      loop:
        - absent
        - directory
    - name: debian | gaps | prepare i3-gaps build
      command: autoreconf --force --install
      args:
        chdir: ~/src/i3-gaps
    - name: debian | gaps | compile
      command: "{{ item }}"
      args:
        chdir: ~/src/i3-gaps/build
      loop:
        - ../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
        - make
    - name: debian | gaps | install i3-gaps
      command: make install
      args:
        chdir: "{{ lookup('env', 'HOME') }}/src/i3-gaps/build"
      become: true
  tags: gaps
  when: ansible_os_family == "Debian"

- name: debian stuff
  block:
    - stat:
        path: /usr/bin/i3
      register: i3_binary
    - name: debian | normal | check if gaps is installed
      command: i3 --version
      register: i3_version
      when: i3_binary.stat.exists
    - name: debian | normal | uninstall gaps
      command: make uninstall
      args:
        chdir: "{{ lookup('env', 'HOME') }}/src/i3-gaps/build"
      when:
        - '"stdout" in i3_version'
        - '"gaps-next" in i3_version.stdout'
    - name: debian | normal | add ppa key
      apt:
        deb: https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2021.02.02_all.deb
    - name: debian | add ppa
      apt_repository:
        repo: >
          deb http://debian.sur5r.net/i3/
          {{ ansible_distribution_release }}
          universe
    - name: debian | normal | install
      apt:
        name:
          - i3
          - i3-wm
          - x11-xserver-utils
  become: true
  when: ansible_os_family == "Debian"
  tags: normal

- name: alpine stuff
  block:
    - name: alpine | normal | install deps
      apk:
        name:
          - i3wm
          - xsetroot
        state: latest
  become: true
  when: ansible_os_family == "Alpine"
  tags: normal
